pipeline {
    agent any

    tools {
        maven 'Maven 3.8.8'
        jdk 'JDK 17'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/btwitsrich/IBMNationalHacks.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('OWASP Dependency-Check') {
            steps {
                bat '''
                    "C:\\Tools\\dependency-check\\bin\\dependency-check.bat" ^
                    --project "IBMNationalHacks" ^
                    --scan "." ^
                    --format "HTML" --format "JSON" ^
                    --out "dependency-check-report"
                '''
            }
        }

        stage('Customize Report') {
            steps {
                writeFile file: 'dependency-check-report/footer.html', text: '''
                    <div style="text-align:center; padding: 15px; margin-top: 40px; background-color: #f7f9fc; border-top: 2px solid #FFA500;">
                        <p style="font-size: 16px; color: #333;">
                            🔒 <strong style="color: #FF5733;">Report generated by Prathamesh</strong> |
                            <span style="color: #007bff;">August 2025</span>
                        </p>
                    </div>
                '''
                bat 'type dependency-check-report\\footer.html >> dependency-check-report\\dependency-check-report.html'
            }
        }
    }

    post {
        success {
            echo 'Build and tests completed successfully.'

            publishHTML(target: [
                reportDir: 'dependency-check-report',
                reportFiles: 'dependency-check-report.html',
                reportName: 'OWASP Dependency-Check Report',
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true
            ])
        }
        failure {
            echo 'Something went wrong with the build.'
        }
    }
}
