pipeline {
    agent any

    tools {
        maven 'Maven 3.8.8'
        jdk 'JDK 17'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/btwitsrich/IBMNationalHacks.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        // ✅ OWASP stage must be *inside* the `stages` block
        stage('OWASP Dependency-Check') {
            steps {
                bat '''
                    "C:\\Tools\\dependency-check\\bin\\dependency-check.bat" ^
                    --project "IBMNationalHacks" ^
                    --scan "." ^
                    --format "HTML"--format "JSON" ^
                    --out "dependency-check-report"
                '''
            }
        }
    }

    stage('Customize Report') {
  steps {
    writeFile file: 'dependency-check-report/footer.html', text: '''
    <footer style="text-align:center; margin-top: 20px;">
      🔒 Report generated by Prathamesh | August 2025
    </footer>
    '''
    bat 'type dependency-check-report\\footer.html >> dependency-check-report\\dependency-check-report.html'
  }
}

    post {
        success {
            echo 'Build and tests completed successfully.'

             publishHTML(target: [
                reportDir: 'dependency-check-report',
                reportFiles: 'dependency-check-report.html',
                reportName: 'OWASP Dependency-Check Report',
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true
            ])
        }
        failure {
            echo 'Something went wrong with the build.'
        }
    }
}
