pipeline {
    agent any

    tools {
        maven 'Maven 3.8.8'
        jdk 'JDK 17'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/btwitsrich/IBMNationalHacks.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('OWASP Dependency-Check') {
            steps {
                bat '''
                    "C:\\Tools\\dependency-check\\bin\\dependency-check.bat" ^
                    --project "IBMNationalHacks" ^
                    --scan "." ^
                    --format "HTML" --format "JSON" ^
                    --out "dependency-check-report"
                '''
            }
        }

        stage('Customize Report') {
            steps {
stage('Customize Report') {
    steps {
        writeFile file: 'dependency-check-report/custom-style.html', text: '''
            <style>
                body {
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    justify-content: center;
                    margin: 0;
                    padding: 20px;
                    font-family: Arial, sans-serif;
                }
                #container {
                    max-width: 1200px;
                    width: 100%;
                }
            </style>
            <script>
                const bodyContent = document.body.innerHTML;
                document.body.innerHTML = "<div id='container'>" + bodyContent + "</div>";
            </script>
            <footer style="text-align:center; padding: 15px; margin-top: 40px; background-color: #f7f9fc;">
                <p style="font-size: 16px; color: #333;">
                    🔒 <strong style="color: #FF5733;">Report generated by Prathamesh</strong> |
                    <span style="color: #007bff;">August 2025</span>
                </p>
            </footer>
        '''
        bat 'type dependency-check-report\\custom-style.html >> dependency-check-report\\dependency-check-report.html'
    }
}

    post {
        success {
            echo 'Build and tests completed successfully.'

            publishHTML(target: [
                reportDir: 'dependency-check-report',
                reportFiles: 'dependency-check-report.html',
                reportName: 'OWASP Dependency-Check Report',
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true
            ])
        }
        failure {
            echo 'Something went wrong with the build.'
        }
    }
            }
